export const commerceCopy = {
  addToCart: { idle: "Add to bag", loading: "Adding…", success: "Added ✓", unavailable: "Currently unavailable" },
  cart: {
    title: "Your bag",
    emptyTitle: "Your bag is empty",
    emptyBody: "Anything you add will wait here until you're ready.",
    startShopping: "Start exploring",
    viewCart: "View bag",
    added: "Added to your bag",
    removed: "Removed from your bag",
  },
  search: {
    placeholder: "Search products, brands and categories",
    trigger: "Search",
    empty: (query: string) => `We couldn't find anything for “${query}”.`,
    emptyHint: "Try checking the spelling or using fewer words.",
    loading: "Looking…",
    recent: "Recent searches",
    clearRecent: "Clear",
    browse: "Browse a space",
    seeAll: (query: string) => `See all results for “${query}”`,
  },
  saved: {
    title: "Saved",
    emptyTitle: "Nothing saved yet",
    emptyBody: "Tap the heart on anything worth a second look. Saved items stay on this device.",
    unavailable: "Some saved items are no longer available and have been hidden.",
  },
  availability: { in_stock: "In stock", low_stock: "Limited availability", out_of_stock: "Currently unavailable" },
} as const;
