using Commerce.Domain;
using Microsoft.EntityFrameworkCore;

namespace Commerce.Infrastructure;

public static class PaymentModelConfiguration
{
    public static void ConfigurePayments(this ModelBuilder model)
    {
        model.Entity<OrderInventoryReservation>(e => { e.ToTable("order_inventory_reservations"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.OrderId, x.WarehouseId, x.VariantId }).IsUnique(); e.HasIndex(x => new { x.ExpiresAt, x.ReleasedAt, x.FulfilledAt }); e.ToTable(t => t.HasCheckConstraint("ck_order_inventory_reservation_quantity", "\"Quantity\" > 0")); e.HasOne<Order>().WithMany().HasForeignKey(x => x.OrderId).OnDelete(DeleteBehavior.Cascade); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<Payment>(e => { e.ToTable("payments"); e.HasKey(x => x.Id); e.Property(x => x.CustomerId).HasMaxLength(200); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.AmountAuthorized).HasPrecision(19, 4); e.Property(x => x.AmountCaptured).HasPrecision(19, 4); e.Property(x => x.AmountRefunded).HasPrecision(19, 4); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(40); e.Property(x => x.Provider).HasMaxLength(80); e.Property(x => x.ProviderPaymentReference).HasMaxLength(200); e.Property(x => x.PaymentMethodType).HasConversion<string>().HasMaxLength(40); e.HasIndex(x => x.OrderId); e.HasIndex(x => new { x.Provider, x.ProviderPaymentReference }).IsUnique().HasFilter("\"ProviderPaymentReference\" IS NOT NULL"); e.HasOne(x => x.Order).WithMany().HasForeignKey(x => x.OrderId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_payment_amounts", "\"AmountAuthorized\" >= 0 AND \"AmountCaptured\" >= 0 AND \"AmountRefunded\" >= 0 AND \"AmountRefunded\" <= \"AmountCaptured\"")); });
        model.Entity<PaymentAttempt>(e => { e.ToTable("payment_attempts"); e.HasKey(x => x.Id); e.Property(x => x.Provider).HasMaxLength(80); e.Property(x => x.ProviderReference).HasMaxLength(200); e.Property(x => x.Amount).HasPrecision(19, 4); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.Method).HasConversion<string>().HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(40); e.Property(x => x.FailureCode).HasMaxLength(100); e.Property(x => x.FailureCategory).HasConversion<string>().HasMaxLength(40); e.Property(x => x.IdempotencyKey).HasMaxLength(128); e.Property(x => x.MetadataJson).HasColumnType("jsonb"); e.HasIndex(x => new { x.PaymentId, x.IdempotencyKey }).IsUnique(); e.HasOne(x => x.Payment).WithMany(x => x.Attempts).HasForeignKey(x => x.PaymentId).OnDelete(DeleteBehavior.Cascade); });
        model.Entity<Refund>(e => { e.ToTable("refunds"); e.HasKey(x => x.Id); e.Property(x => x.Amount).HasPrecision(19, 4); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.Reason).HasMaxLength(500); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.ProviderRefundReference).HasMaxLength(200); e.Property(x => x.RequestedBy).HasMaxLength(64); e.Property(x => x.IdempotencyKey).HasMaxLength(128); e.HasIndex(x => new { x.PaymentId, x.IdempotencyKey }).IsUnique(); e.HasOne(x => x.Payment).WithMany(x => x.Refunds).HasForeignKey(x => x.PaymentId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_refund_amount", "\"Amount\" > 0")); });
        model.Entity<PaymentWebhookEvent>(e => { e.ToTable("payment_webhook_events"); e.HasKey(x => x.Id); e.Property(x => x.Provider).HasMaxLength(80); e.Property(x => x.ProviderEventId).HasMaxLength(200); e.Property(x => x.EventType).HasMaxLength(100); e.Property(x => x.ProcessingStatus).HasConversion<string>().HasMaxLength(30); e.Property(x => x.FailureCode).HasMaxLength(100); e.Property(x => x.PayloadHash).HasMaxLength(64); e.HasIndex(x => new { x.Provider, x.ProviderEventId }).IsUnique(); });
        model.Entity<PaymentReconciliation>(e => { e.ToTable("payment_reconciliations"); e.HasKey(x => x.Id); e.Property(x => x.Provider).HasMaxLength(80); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.ProviderCapturedAmount).HasPrecision(19, 4); e.Property(x => x.ProviderRefundedAmount).HasPrecision(19, 4); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.Detail).HasMaxLength(500); e.Property(x => x.EvaluatedBy).HasMaxLength(64); e.HasIndex(x => new { x.PaymentId, x.EvaluatedAt }); });
        model.Entity<InstallmentPlan>(e => { e.ToTable("installment_plans"); e.HasKey(x => x.Id); e.Property(x => x.Provider).HasMaxLength(80); e.Property(x => x.ProviderPlanId).HasMaxLength(200); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.TotalAmount).HasPrecision(19, 4); e.Property(x => x.CustomerCost).HasPrecision(19, 4); e.Property(x => x.MerchantCost).HasPrecision(19, 4); e.Property(x => x.Frequency).HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.TermsReference).HasMaxLength(500); e.HasIndex(x => x.PaymentId).IsUnique(); });
        model.Entity<InstallmentSchedule>(e => { e.ToTable("installment_schedules"); e.HasKey(x => x.Id); e.Property(x => x.Amount).HasPrecision(19, 4); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.ProviderPaymentReference).HasMaxLength(200); e.HasIndex(x => new { x.InstallmentPlanId, x.Sequence }).IsUnique(); e.HasOne(x => x.Plan).WithMany(x => x.Schedule).HasForeignKey(x => x.InstallmentPlanId).OnDelete(DeleteBehavior.Cascade); });
    }
}
