using Commerce.Domain;
using Microsoft.EntityFrameworkCore;

namespace Commerce.Infrastructure;

internal static class SupplyChainModelConfiguration
{
    public static void ConfigureSupplyChain(this ModelBuilder model)
    {
        model.Entity<SupplierOrganization>(e => { e.ToTable("supplier_organizations"); e.HasKey(x => x.Id); e.Property(x => x.Code).HasMaxLength(40); e.Property(x => x.LegalName).HasMaxLength(240); e.Property(x => x.CountryCode).HasMaxLength(2).IsFixedLength(); e.Property(x => x.TaxIdentifier).HasMaxLength(80); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => x.Code).IsUnique(); });
        model.Entity<SupplierUser>(e => { e.ToTable("supplier_users"); e.HasKey(x => new { x.SupplierOrganizationId, x.ApplicationUserId }); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Cascade); e.HasOne<ApplicationUser>().WithMany().HasForeignKey(x => x.ApplicationUserId).OnDelete(DeleteBehavior.Cascade); });
        model.Entity<SupplierProductSource>(e => { e.ToTable("supplier_product_sources"); e.HasKey(x => x.Id); e.Property(x => x.SupplierSku).HasMaxLength(80); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.UnitCost).HasPrecision(19, 4); e.Property(x => x.ReliabilityPercent).HasPrecision(6, 3); e.HasIndex(x => new { x.SupplierOrganizationId, x.VariantId, x.SupplierSku }).IsUnique(); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_supplier_source_values", "\"UnitCost\" >= 0 AND \"LeadTimeDays\" >= 0 AND \"MinimumOrderQuantity\" > 0 AND \"OrderMultiple\" > 0 AND (\"ReliabilityPercent\" IS NULL OR \"ReliabilityPercent\" BETWEEN 0 AND 100)")); });
        model.Entity<RequestForQuotation>(e => { e.ToTable("requests_for_quotation"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.CreatedBy).HasMaxLength(64); e.Property(x => x.AwardReason).HasMaxLength(500); e.Property(x => x.AwardedBy).HasMaxLength(64); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.Status, x.ResponseDeadline }); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); e.HasOne<SupplierQuotation>().WithMany().HasForeignKey(x => new { x.AwardedQuotationId, RequestForQuotationId = x.Id }).HasPrincipalKey(x => new { AwardedQuotationId = (Guid?)x.Id, x.RequestForQuotationId }).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<RequestForQuotationLine>(e => { e.ToTable("request_for_quotation_lines"); e.HasKey(x => x.Id); e.HasAlternateKey(x => new { x.Id, x.RequestForQuotationId }); e.HasIndex(x => new { x.RequestForQuotationId, x.VariantId }).IsUnique(); e.HasOne(x => x.RequestForQuotation).WithMany(x => x.Lines).HasForeignKey(x => x.RequestForQuotationId).OnDelete(DeleteBehavior.Cascade); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_rfq_line_quantity", "\"Quantity\" > 0")); });
        model.Entity<RequestForQuotationSupplier>(e => { e.ToTable("request_for_quotation_suppliers"); e.HasKey(x => new { x.RequestForQuotationId, x.SupplierOrganizationId }); e.HasOne<RequestForQuotation>().WithMany(x => x.Suppliers).HasForeignKey(x => x.RequestForQuotationId).OnDelete(DeleteBehavior.Cascade); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<SupplierQuotation>(e => { e.ToTable("supplier_quotations"); e.HasKey(x => x.Id); e.HasAlternateKey(x => new { x.Id, x.RequestForQuotationId }); e.HasAlternateKey(x => new { x.Id, x.SupplierOrganizationId }); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.RequestHash).HasMaxLength(64).IsFixedLength(); e.Property(x => x.SubmittedBy).HasMaxLength(64); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.RequestForQuotationId, x.SupplierOrganizationId }).IsUnique(); e.HasOne<RequestForQuotation>().WithMany().HasForeignKey(x => x.RequestForQuotationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<SupplierQuotationLine>(e => { e.ToTable("supplier_quotation_lines"); e.HasKey(x => x.Id); e.Property(x => x.SupplierSku).HasMaxLength(80); e.Property(x => x.UnitCost).HasPrecision(19, 4); e.Property(x => x.ReliabilityPercent).HasPrecision(6, 3); e.HasIndex(x => new { x.SupplierQuotationId, x.RequestForQuotationLineId }).IsUnique(); e.HasOne(x => x.SupplierQuotation).WithMany(x => x.Lines).HasForeignKey(x => new { x.SupplierQuotationId, x.RequestForQuotationId }).HasPrincipalKey(x => new { x.Id, x.RequestForQuotationId }).OnDelete(DeleteBehavior.Cascade); e.HasOne(x => x.RequestForQuotationLine).WithMany().HasForeignKey(x => new { Id = x.RequestForQuotationLineId, x.RequestForQuotationId }).HasPrincipalKey(x => new { x.Id, x.RequestForQuotationId }).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_quotation_line_values", "\"UnitCost\" >= 0 AND \"LeadTimeDays\" >= 0 AND \"MinimumOrderQuantity\" > 0 AND \"OrderMultiple\" > 0 AND (\"ReliabilityPercent\" IS NULL OR \"ReliabilityPercent\" BETWEEN 0 AND 100)")); });
        model.Entity<PurchaseOrder>(e => { e.ToTable("purchase_orders"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.CreatedBy).HasMaxLength(64); e.Property(x => x.ApprovedBy).HasMaxLength(64); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.SupplierOrganizationId, x.Status, x.CreatedAt }); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); e.HasOne<SupplierQuotation>().WithMany().HasForeignKey(x => new { x.SourceQuotationId, x.SupplierOrganizationId }).HasPrincipalKey(x => new { SourceQuotationId = (Guid?)x.Id, x.SupplierOrganizationId }).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<PurchaseOrderLine>(e => { e.ToTable("purchase_order_lines"); e.HasKey(x => x.Id); e.Property(x => x.SupplierSku).HasMaxLength(80); e.Property(x => x.UnitCost).HasPrecision(19, 4); e.Property(x => x.ReliabilityPercent).HasPrecision(6, 3); e.HasIndex(x => new { x.PurchaseOrderId, x.VariantId }).IsUnique(); e.HasOne(x => x.PurchaseOrder).WithMany(x => x.Lines).HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Cascade); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.HasOne<SupplierQuotationLine>().WithMany().HasForeignKey(x => x.SourceQuotationLineId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_purchase_order_line_quantity", "\"OrderedQuantity\" > 0 AND \"ReceivedQuantity\" >= 0 AND \"ReceivedQuantity\" <= \"OrderedQuantity\" AND \"UnitCost\" >= 0 AND \"LeadTimeDays\" >= 0 AND \"MinimumOrderQuantity\" > 0 AND \"OrderMultiple\" > 0 AND (\"ReliabilityPercent\" IS NULL OR \"ReliabilityPercent\" BETWEEN 0 AND 100)")); });
        model.Entity<InboundShipment>(e => { e.ToTable("inbound_shipments"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.Carrier).HasMaxLength(120); e.Property(x => x.TrackingNumber).HasMaxLength(160); e.Property(x => x.IdempotencyKey).HasMaxLength(128); e.Property(x => x.RequestHash).HasMaxLength(64).IsFixedLength(); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.SupplierOrganizationId, x.IdempotencyKey }).IsUnique(); e.HasIndex(x => new { x.SupplierOrganizationId, x.Status }); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<PurchaseOrder>().WithMany().HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<InboundShipmentLine>(e => { e.ToTable("inbound_shipment_lines"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.InboundShipmentId, x.PurchaseOrderLineId }).IsUnique(); e.HasOne(x => x.InboundShipment).WithMany(x => x.Lines).HasForeignKey(x => x.InboundShipmentId).OnDelete(DeleteBehavior.Cascade); e.HasOne<PurchaseOrderLine>().WithMany().HasForeignKey(x => x.PurchaseOrderLineId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_inbound_line_quantity", "\"ExpectedQuantity\" > 0")); });
        model.Entity<FiscalInvoice>(e => { e.ToTable("fiscal_invoices"); e.HasKey(x => x.Id); e.Property(x => x.Provider).HasMaxLength(80); e.Property(x => x.ExternalNumber).HasMaxLength(120); e.Property(x => x.Currency).HasMaxLength(3).IsFixedLength(); e.Property(x => x.TotalAmount).HasPrecision(19, 4); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.PayloadHash).HasMaxLength(64).IsFixedLength(); e.Property(x => x.RequestHash).HasMaxLength(64).IsFixedLength(); e.Property(x => x.DocumentReference).HasMaxLength(1000); e.HasIndex(x => new { x.SupplierOrganizationId, x.Provider, x.ExternalNumber }).IsUnique(); e.HasIndex(x => new { x.SupplierOrganizationId, x.PayloadHash }).IsUnique(); e.HasOne<SupplierOrganization>().WithMany().HasForeignKey(x => x.SupplierOrganizationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<PurchaseOrder>().WithMany().HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<FiscalInvoiceLine>(e => { e.ToTable("fiscal_invoice_lines"); e.HasKey(x => x.Id); e.Property(x => x.SupplierSku).HasMaxLength(80); e.Property(x => x.UnitCost).HasPrecision(19, 4); e.HasIndex(x => new { x.FiscalInvoiceId, x.PurchaseOrderLineId }).IsUnique().HasFilter("\"PurchaseOrderLineId\" IS NOT NULL"); e.HasOne(x => x.FiscalInvoice).WithMany(x => x.Lines).HasForeignKey(x => x.FiscalInvoiceId).OnDelete(DeleteBehavior.Cascade); e.HasOne<PurchaseOrderLine>().WithMany().HasForeignKey(x => x.PurchaseOrderLineId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_invoice_line_values", "\"Quantity\" > 0 AND \"UnitCost\" >= 0")); });
        model.Entity<InventoryLot>(e => { e.ToTable("inventory_lots"); e.HasKey(x => x.Id); e.Property(x => x.LotNumber).HasMaxLength(120); e.HasIndex(x => new { x.VariantId, x.LotNumber }).IsUnique(); e.HasIndex(x => x.ExpiresAt); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<InventoryBalance>(e => { e.ToTable("inventory_balances"); e.HasKey(x => x.Id); e.Property(x => x.State).HasConversion<string>().HasMaxLength(30); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => new { x.WarehouseId, x.LocationId, x.VariantId, x.LotId, x.State }).IsUnique().AreNullsDistinct(false); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLocation>().WithMany().HasForeignKey(x => x.LocationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLot>().WithMany().HasForeignKey(x => x.LotId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_inventory_balance_nonnegative", "\"Quantity\" >= 0")); });
        model.Entity<GoodsReceipt>(e => { e.ToTable("goods_receipts"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.IdempotencyKey).HasMaxLength(128); e.Property(x => x.RequestHash).HasMaxLength(64).IsFixedLength(); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.ReceivedBy).HasMaxLength(64); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => x.IdempotencyKey).IsUnique(); e.HasOne<PurchaseOrder>().WithMany().HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InboundShipment>().WithMany().HasForeignKey(x => x.InboundShipmentId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<GoodsReceiptLine>(e => { e.ToTable("goods_receipt_lines"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.GoodsReceiptId, x.PurchaseOrderLineId }).IsUnique(); e.HasOne(x => x.GoodsReceipt).WithMany(x => x.Lines).HasForeignKey(x => x.GoodsReceiptId).OnDelete(DeleteBehavior.Cascade); e.HasOne<PurchaseOrderLine>().WithMany().HasForeignKey(x => x.PurchaseOrderLineId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLot>().WithMany().HasForeignKey(x => x.LotId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_receipt_line_quantities", "\"ExpectedQuantity\" > 0 AND \"PhysicalQuantity\" >= 0 AND \"AcceptedQuantity\" >= 0 AND \"DamagedQuantity\" >= 0 AND \"QuarantinedQuantity\" >= 0 AND \"MissingQuantity\" >= 0 AND \"PhysicalQuantity\" = \"AcceptedQuantity\" + \"DamagedQuantity\" + \"QuarantinedQuantity\" AND \"MissingQuantity\" = GREATEST(\"ExpectedQuantity\" - \"PhysicalQuantity\", 0)")); });
        model.Entity<InvoiceMatch>(e => { e.ToTable("invoice_matches"); e.HasKey(x => x.Id); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.ExceptionsJson).HasColumnType("jsonb"); e.HasIndex(x => x.FiscalInvoiceId).IsUnique(); e.HasOne<PurchaseOrder>().WithMany().HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); e.HasOne<FiscalInvoice>().WithMany().HasForeignKey(x => x.FiscalInvoiceId).OnDelete(DeleteBehavior.Restrict); });
    }
}
