using Commerce.Domain;
using Microsoft.EntityFrameworkCore;

namespace Commerce.Infrastructure;

internal static class WarehouseExecutionModelConfiguration
{
    public static void ConfigureWarehouseExecution(this ModelBuilder model)
    {
        model.Entity<WarehouseTask>(e => { e.ToTable("warehouse_tasks"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Type).HasConversion<string>().HasMaxLength(30); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.InventoryState).HasConversion<string>().HasMaxLength(30); e.Property(x => x.ReferenceType).HasMaxLength(60); e.Property(x => x.ReferenceId).HasMaxLength(120); e.Property(x => x.AssignedTo).HasMaxLength(64); e.Property(x => x.CreatedBy).HasMaxLength(64); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.ReferenceType, x.ReferenceId }).IsUnique(); e.HasIndex(x => new { x.WarehouseId, x.Status, x.Priority, x.CreatedAt }); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLocation>().WithMany().HasForeignKey(x => x.SourceLocationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLocation>().WithMany().HasForeignKey(x => x.DestinationLocationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLot>().WithMany().HasForeignKey(x => x.LotId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_warehouse_task_quantities", "\"Quantity\" >= 0 AND \"CompletedQuantity\" >= 0 AND \"CompletedQuantity\" <= \"Quantity\" AND \"Priority\" BETWEEN 0 AND 100")); });
        model.Entity<CycleCount>(e => { e.ToTable("cycle_counts"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.CreatedBy).HasMaxLength(64); e.Property(x => x.CountedBy).HasMaxLength(64); e.Property(x => x.ReconciledBy).HasMaxLength(64); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.WarehouseId, x.Status, x.CreatedAt }); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); });
        model.Entity<CycleCountLine>(e => { e.ToTable("cycle_count_lines"); e.HasKey(x => x.Id); e.Property(x => x.State).HasConversion<string>().HasMaxLength(30); e.HasIndex(x => new { x.CycleCountId, x.VariantId, x.LocationId, x.LotId, x.State }).IsUnique().AreNullsDistinct(false); e.HasOne(x => x.CycleCount).WithMany(x => x.Lines).HasForeignKey(x => x.CycleCountId).OnDelete(DeleteBehavior.Cascade); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLocation>().WithMany().HasForeignKey(x => x.LocationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLot>().WithMany().HasForeignKey(x => x.LotId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_cycle_count_quantities", "\"ExpectedQuantity\" >= 0 AND (\"CountedQuantity\" IS NULL OR \"CountedQuantity\" >= 0)")); });
        model.Entity<StockTransfer>(e => { e.ToTable("stock_transfers"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(40); e.Property(x => x.Status).HasConversion<string>().HasMaxLength(30); e.Property(x => x.CreatedBy).HasMaxLength(64); e.Property(x => x.CreateIdempotencyKey).HasMaxLength(128); e.Property(x => x.CreateRequestHash).HasMaxLength(64); e.Property(x => x.DispatchedBy).HasMaxLength(64); e.Property(x => x.DispatchIdempotencyKey).HasMaxLength(128); e.Property(x => x.ReceivedBy).HasMaxLength(64); e.Property(x => x.ReceiveIdempotencyKey).HasMaxLength(128); e.Property(x => x.Version).IsRowVersion(); e.HasIndex(x => x.Number).IsUnique(); e.HasIndex(x => new { x.Status, x.CreatedAt }); e.HasIndex(x => x.CreateIdempotencyKey).IsUnique(); e.HasIndex(x => x.DispatchIdempotencyKey).IsUnique().HasFilter("\"DispatchIdempotencyKey\" IS NOT NULL"); e.HasIndex(x => x.ReceiveIdempotencyKey).IsUnique().HasFilter("\"ReceiveIdempotencyKey\" IS NOT NULL"); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.FromWarehouseId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Warehouse>().WithMany().HasForeignKey(x => x.ToWarehouseId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_stock_transfer_warehouses", "\"FromWarehouseId\" <> \"ToWarehouseId\"")); });
        model.Entity<StockTransferLine>(e => { e.ToTable("stock_transfer_lines"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.StockTransferId, x.VariantId, x.LotId }).IsUnique().AreNullsDistinct(false); e.HasOne(x => x.StockTransfer).WithMany(x => x.Lines).HasForeignKey(x => x.StockTransferId).OnDelete(DeleteBehavior.Cascade); e.HasOne<ProductVariant>().WithMany().HasForeignKey(x => x.VariantId).OnDelete(DeleteBehavior.Restrict); e.HasOne<InventoryLot>().WithMany().HasForeignKey(x => x.LotId).OnDelete(DeleteBehavior.Restrict); e.ToTable(t => t.HasCheckConstraint("ck_stock_transfer_line_quantity", "\"Quantity\" > 0")); });
    }
}
